### ISSUE TITLE
Bug if no Merge data provided in info array

### ISSUE THREAD

**Issue by pospelovanm** [JPeer264/node-git-commit-info#14]
Hello, @JPeer264!
We use this library in our project.  However, there is a bug in the package on [this line](https://github.com/JPeer264/node-git-commit-info/blob/master/index.ts#L42).
Blows up if `info[1]` is empty.

I've fixed it locally. Can I make PR?

**Comment by JPeer264** [comment]
Hey @pospelovanm . Sure if you have fixed that bug already please do so.

**Comment by pospelovanm** [comment]
I try to make PR but got an error "Permission to JPeer264/node-git-commit-info.git denied to pospelovanm". Maybe I don't have write access. If it's true I can leave changes here (it's just 1 line of code).

**Comment by JPeer264** [comment]
You can leave the changes here as well if you want and I can change it. But if you still want to do it you need to `Fork` (on the top right) the project first and commit everything to your project to be able to create a pull request.

**Comment by pospelovanm** [comment]
I'll leave here)).

//index.ts
 42 `const mergeIndex = info.length > 1 && info[1].indexOf('Merge') !== -1 ? 1 : 0;`

**Comment by pospelovanm** [comment]
@JPeer264, I don't want to seem annoying, but I've left comment.
What do you say?

**Comment by JPeer264** [comment]
I am super sorry. I was overseeing this. Thanks a lot for your help, I will implement it right away.

**Comment by JPeer264** [comment]
I published it with v`2.0.1`. Please let me know if it works for you now.
