### ISSUE TITLE
Version 1.1.0 release

### ISSUE THREAD

**Issue by npalmius** [JPeer264/node-git-commit-info#6]
Version 1.1.0, with the merge commit fix, is tagged, but I can't see it on npm. Is it published anywhere?

**Comment by JPeer264** [comment]
Huh, you are right. I'm sorry, I will publish it when I am at home ;)

**Comment by JPeer264** [comment]
Alright, I just published v1.1.0. Thanks a lot for the hint.

**Comment by JPeer264** [comment]
But actually I think I have to fix this one again, as there is a more reliable way of checking for merge commits.

**Comment by npalmius** [comment]
Many thanks Jan!
